// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  career_fields: dynamic(() => import('./CareerFields')),
  info_box: dynamic(() => import('./InfoBox')),
  job: dynamic(() => import('./Job')),
  process_steps: dynamic(() => import('./ProcessSteps')),
};
