// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  sponsor: dynamic(() => import('./Sponsor')),
  tournament_faqs: dynamic(() => import('./TournamentFaqs')),
};
