from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime

class CurrencyRate(BaseModel):
    currency_code: str = Field(alias="CurrencyCode")
    value: float = Field(alias="Value")

class CustomField(BaseModel):
    field_name: str = Field(alias="FieldName")
    value: List[str] = Field(alias="Value")
    action: str = Field(alias="Action")

class CandidateInfo(BaseModel):
    candidate_id: Optional[int] = Field(alias="CandidateId")
    company_id: Optional[int] = Field(alias="CompanyId")
    first_name: Optional[str] = Field(alias="FirstName")
    last_name: Optional[str] = Field(alias="LastName")
    middle_initial: Optional[str] = Field(default=None, alias="MiddleInitial")
    salutation: Optional[str] = Field(default=None, alias="Salutation")
    title: Optional[str] = Field(default=None, alias="Title")
    address: Optional[str] = Field(default=None, alias="Address")
    address2: Optional[str] = Field(default=None, alias="Address2")
    city: Optional[str] = Field(default=None, alias="City")
    state: Optional[str] = Field(default=None, alias="State")
    postal_code: Optional[str] = Field(default=None, alias="PostalCode")
    postal_code_extension: Optional[str] = Field(default=None, alias="PostalCodeExtension")
    full_postal_code: Optional[str] = Field(default=None, alias="FullPostalCode")
    county: Optional[str] = Field(default=None, alias="County")
    country: Optional[str] = Field(default=None, alias="Country")
    home_phone: Optional[str] = Field(default=None, alias="HomePhone")
    fax_phone: Optional[str] = Field(default=None, alias="FaxPhone")
    pager: Optional[str] = Field(default=None, alias="Pager")
    mobile_phone: Optional[str] = Field(default=None, alias="MobilePhone")
    work_phone: Optional[str] = Field(default=None, alias="WorkPhone")
    current_occupation: Optional[str] = Field(default=None, alias="CurrentOccupation")
    relocate: Optional[str] = Field(default=None, alias="Relocate")
    current_salary: Optional[float] = Field(default=None, alias="CurrentSalary")
    desired_salary: Optional[float] = Field(default=None, alias="DesiredSalary")
    school: Optional[str] = Field(default=None, alias="School")
    degree_type: Optional[str] = Field(default=None, alias="DegreeType")
    grad_year: Optional[int] = Field(default=None, alias="GradYear")
    date_entered: Optional[datetime] = Field(default_factory=datetime.now, alias="DateEntered")
    email_address: str = Field(alias="EmailAddress")
    industry: Optional[str] = Field(default=None, alias="Industry")
    specialty: Optional[str] = Field(default=None, alias="Specialty")
    show_on_web_rollup: Optional[bool] = Field(default=None, alias="ShowOnWebRollup")
    status: Optional[str] = Field(alias="Status")
    subjective: Optional[int] = Field(alias="Subjective")
    has_resume: Optional[bool] = Field(alias="HasResume")
    identification: Optional[str] = Field(alias="Identification")
    last_activity: Optional[datetime] = Field(alias="LastActivity")
    last_modified: Optional[datetime] = Field(alias="LastModified")
    available: Optional[datetime] = Field(alias="Available")
    bill_rate: Optional[CurrencyRate] = Field(alias="BillRate")
    pay_rate: Optional[CurrencyRate] = Field(alias="PayRate")
    default_currency: Optional[str] = Field(alias="DefaultCurrency")
    user_name: Optional[str] = Field(alias="UserName")
    group: Optional[str] = Field(alias="Group")
    custom_fields: Optional[List[CustomField]] = Field(alias="CustomFields")
