name: Mirror Repo

on: [push, pull_request]

jobs:
  build:
    if: github.repository == 'AprovanLabs/lotus'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Mirror
        # Remove the extraheader that is set by the checkout action
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git config --global core.compression 9
          git fetch --unshallow
          git gc
          git fsck
          git push --no-thin --mirror https://${{secrets.EXTERNAL_GITHUB_TOKEN}}@github.com/AprovanBot/lotus.git
